title: UBC Computer Science Student Society
email: csss@ubccsss.org
description: >
  Welcome to the Computer Science Student Society, the student club for
  undergraduates at the UBC Department of Computer Science. We provide a social
  space where everyone’s welcome (in ICICS 021), run events, and represent your
  interests to the department. For more events you may be interested in, please
  see the department's calendar. Please feel free to email us at
  csss@ubccsss.org.
baseurl: ""
url: "https://ubccsss.org"
twitter_username: ubccsss
github_username: ubccsss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
