# baseURL: "https://ubccsss.org/"
baseURL: "https://ubc-csss.netlify.com/"
languageCode: "en-ca"
title: UBC CSSS
theme: hugo-bootstrap
googleAnalytics: UA-88004303-1

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: -140
    - identifier: volunteer
      name: Volunteer
      url: /volunteer
      weight: -130
    - identifier: cube
      name: The Cube
      url: /cube
      weight: -120
    - identifier: learn
      name: Services
      url: /services
      weight: -110
    - identifier: contact
      name: Contact
      url: /contact
      weight: -100

frontmatter:
  date:
    - ":filename"
    - ":default"

default_location_address:
  addressLocality: Vancouver
  addressRegion: BC
  addressCountry: CA

permalinks:
  posts: /posts/:year/:month/:title/
  events: /events/:year/:month/:title/
  minutes: /about/minutes/:year/:month/:day/

paginate: 5

params:
  eventSections:
    - events
  mainSections:
    - events
    - posts
    - career
  truncate: false
  header:
    colorScheme: dark
  footer:
    colorScheme: dark
